server:
  port: 9500
spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:9000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true